name: Publish Provider Packages

on:
  workflow_dispatch:
    inputs:
      subpackages:
        description: 'Subpackages to be built individually (e.g. config ec2)'
        default: 'config'
        required: false
      size:
        description: "Number of smaller provider packages to build and push with each build job"
        default: '30'
        required: true
      concurrency:
        description: "Number of parallel package builds within each build job"
        default: '1'
        required: false
      version:
        description: "Version string to use while publishing the packages (e.g. v1.0.0-alpha.1)"
        default: ''
        required: false
      go-version:
        description: 'Go version to use if building needs to be done'
        default: '1.25.11'
        required: false
      platforms:
        description: "Space-separated make platforms (for example: linux_amd64 linux_arm64)"
        default: 'linux_amd64 linux_arm64'
        required: false
      batch-platforms:
        description: "Comma-separated xpkg batch platforms (for example: linux_amd64,linux_arm64)"
        default: 'linux_amd64,linux_arm64'
        required: false

permissions:
  contents: read
  packages: write

jobs:
  publish-provider-packages:
    uses: ./.github/workflows/publish-provider-family.yml
    with:
      subpackages: ${{ github.event.inputs.subpackages }}
      size: ${{ github.event.inputs.size }}
      concurrency: ${{ github.event.inputs.concurrency }}
      repository: provider-azure
      version: ${{ github.event.inputs.version }}
      go-version: ${{ github.event.inputs.go-version }}
      platforms: ${{ github.event.inputs.platforms }}
      batch-platforms: ${{ github.event.inputs.batch-platforms }}
      cleanup-disk: true
      runs-on: ubuntu-latest
      mirror-to-upbound-registry: false
